services:
  nuxt-app:
    build: .
    container_name: nuxt-dev-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents overriding node_modules with local copy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres-db:5432/mydatabase
    command: npm run dev
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
